### ISSUE TITLE
代码运行时异常求解

### ISSUE THREAD

**Issue by heheha-bit** [re-ovo/iwara4a#51]
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:244)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x7de3d47388: I/O error during system call, Connection reset by peer
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:284)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x7de3d47388: I/O error during system call, Connection reset by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:385)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:342)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:213)
        at okhttp3.internal.connection.RealRoutePlanner$RealConnectPlan.connect(RealRoutePlanner.kt:220)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:31)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:265)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:75)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.rerere.iwara4a.util.okhttp.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:16)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:279)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

初步DeBug在调用VideoViewModel.kt下loadVideo后网络环境波动时会有概率出现,只会导致视频无法正常加载播放,其他无任何影响

经过检查HotDNS解析的i站ip，与在cloudflare CDN有免费加速的i站域名ip一致，初步判断有加速效果，因此我将作者您的代码DNS部分进行了修改使其解析的i站ip强行指向cloudflare CDN，实现了全程加速直连无卡顿加载，但需要增加暴力请求次数上限来确保i站土豆服务器正常响应。
![截图](https://user-images.githubusercontent.com/63770878/167123969-f2bd15d6-53a3-4d6f-9569-8e415ff36deb.png)

**Comment by heheha-bit** [comment]
> 这个错误是你强制指向CF后出现的吗

我没有去测试其他情况，我这个的确是强制指向后出现的异常，时有时无，主要是我抓不到他这个异常，构建异常抓捕器也不知到该往哪构造，就来请教一下了

**Comment by re-ovo** [comment]
不清楚，可能是SSL验证的问题，我也不懂

**Comment by VoidxHoshi** [comment]
HotDNS是啥？
截图是什么软件呀？看起来像浏览器插件。
我试过你那个方法，可能是地区原因，还没我直连快。

**Comment by re-ovo** [comment]
只要不在国内的服务器，都会统一被丢包，我不觉得不靠梯子能稳定看上视频

**Comment by re-ovo** [comment]
> HotDNS是啥？ 截图是什么软件呀？看起来像浏览器插件。 我试过你那个方法，可能是地区原因，还没我直连快。

他那是Cloudflare官网

**Comment by heheha-bit** [comment]
> 只要不在国内的服务器，都会统一被丢包，我不觉得不靠梯子能稳定看上视频

主要是有时候高质量的梯子不是时时都有

**Comment by heheha-bit** [comment]
> HotDNS是啥？ 截图是什么软件呀？看起来像浏览器插件。 我试过你那个方法，可能是地区原因，还没我直连快。

加密DNS防污染的字写错了

**Comment by re-ovo** [comment]
> > 只要不在国内的服务器，都会统一被丢包，我不觉得不靠梯子能稳定看上视频
> 
> 主要是有时候高质量的梯子不是时时都有

有的，加钱就行了

**Comment by heheha-bit** [comment]
> HotDNS是啥？ 截图是什么软件呀？看起来像浏览器插件。 我试过你那个方法，可能是地区原因，还没我直连快。

我今天试了改了一下作者的项目，只要能响应一次就可以全站无卡顿，不过每个地区最快的ip不同，要本地测试才行，我这是被梯子卡的没办法了，才起了兴趣搞得

**Comment by re-ovo** [comment]
> > HotDNS是啥？ 截图是什么软件呀？看起来像浏览器插件。 我试过你那个方法，可能是地区原因，还没我直连快。
> 
> 我今天试了改了一下作者的项目，只要能响应一次就可以全站无卡顿，不过每个地区最快的ip不同，要本地测试才行，我这是被梯子卡的没办法了，才起了兴趣搞得

买个IEPL线路的梯就行了，一年六七百
